name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup environment
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip openjdk-11-jdk git zip unzip wget
        
    - name: Install buildozer
      run: pip install buildozer cython
        
    - name: Force accept all Android licenses
      run: |
        # Método más agresivo para aceptar licencias
        mkdir -p ~/.android
        touch ~/.android/repositories.cfg
        
        yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses > /dev/null 2>&1 || true
        
        # Crear archivos de licencia manualmente
        mkdir -p $ANDROID_SDK_ROOT/licenses
        for i in {1..10}; do
          echo "Aceptando licencia $i..."
          echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" >> $ANDROID_SDK_ROOT/licenses/android-sdk-license
          echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" >> $ANDROID_SDK_ROOT/licenses/android-sdk-preview-license
        done
        
    - name: Build with forced license acceptance
      run: |
        export PATH=$PATH:~/.local/bin
        
        # Configurar variables de entorno críticas
        export ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT
        export ANDROID_NDK_HOME=/usr/local/lib/android/sdk/ndk/25.1.8937393
        
        # Forzar la actualización del SDK
        buildozer android clean
        buildozer android updatesdk --yes
        
        # Compilar
        buildozer android debug
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: AppListGenerator-APK
        path: bin/*.apk
        retention-days: 30
