name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-pip \
          autoconf \
          automake \
          build-essential \
          ccache \
          libffi-dev \
          libltdl-dev \
          libssl-dev \
          openjdk-11-jdk \
          unzip \
          zlib1g-dev
        
    - name: Install Buildozer
      run: pip3 install --user buildozer
      
    - name: Accept Android SDK licenses
      run: |
        yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses
        
    - name: Build APK with detailed logging
      run: |
        export PATH=$PATH:~/.local/bin
        buildozer -v android debug 2>&1 | tail -200
        
    - name: Upload APK
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: AppListGenerator-APK
        path: bin/*.apk
        retention-days: 30
