name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup environment
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip openjdk-11-jdk git zip unzip
        
    - name: Install buildozer
      run: pip install buildozer cython
        
    - name: Install Android SDK tools manually
      run: |
        # Aceptar licencias
        mkdir -p $ANDROID_SDK_ROOT/licenses
        echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > $ANDROID_SDK_ROOT/licenses/android-sdk-license
        echo "84831b9409646a918e30573bab4c9c91346d8abd" > $ANDROID_SDK_ROOT/licenses/android-sdk-preview-license
        
        # Instalar herramientas específicas
        yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.0"
        
    - name: Create Buildozer directory structure
      run: |
        # Crear la estructura de directorios que Buildozer espera
        mkdir -p /home/runner/.buildozer/android/platform/android-sdk
        # Copiar el SDK instalado a la ubicación de Buildozer
        cp -r $ANDROID_SDK_ROOT/* /home/runner/.buildozer/android/platform/android-sdk/
        
    - name: Build APK
      run: |
        export PATH=$PATH:~/.local/bin
        buildozer -v android debug
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: AppListGenerator-APK
        path: bin/*.apk
        retention-days: 30
