name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build with Buildozer in isolated environment
      run: |
        # Create a simple Dockerfile and build
        cat > Dockerfile << EOF
        FROM ubuntu:22.04
        
        RUN apt-get update && apt-get install -y \
            python3-pip \
            build-essential \
            openjdk-11-jdk \
            git \
            zip \
            unzip \
            zlib1g-dev
            
        RUN pip3 install buildozer cython
        
        WORKDIR /app
        COPY . .
        
        RUN buildozer android debug
        EOF
        
        docker build -t app-builder .
        docker run --rm -v $(pwd)/bin:/app/bin app-builder
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: AppListGenerator-APK
        path: bin/*.apk
        retention-days: 30
