name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup environment
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip openjdk-11-jdk git zip unzip
        
    - name: Install buildozer
      run: pip install buildozer cython
        
    - name: Install Android tools with specific version
      run: |
        # Método directo: instalar una versión OLDER de build-tools que no pida licencia
        $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager "build-tools;30.0.3" "platforms;android-33" "platform-tools"
        
    - name: Build APK
      run: |
        export PATH=$PATH:~/.local/bin
        buildozer android debug
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: AppListGenerator-APK
        path: bin/*.apk
        retention-days: 30
